@startuml
'https://plantuml.com/sequence-diagram
'skinparam monochrome true
skinparam shadowing false
skinparam ParticipantBackgroundColor white
'autonumber

alt guard1
A -> B: message1
B -> A: message2
else guard2
A -> B: message3
A <- B: message4
end
@enduml