@startuml
'https://plantuml.com/sequence-diagram
'skinparam monochrome true
skinparam shadowing false
skinparam ParticipantBackgroundColor white
'autonumber

loop a guard
A -> B: message1
B -> A: message2
end
@enduml